import { type Friend, type Restaurant } from "./types"

export const Friends: Friend[] = [
    { id: "1", name: "Ambroise" },
    { id: "2", name: "Aurélien" },
    { id: "3", name: "Giovanni" },
    { id: "4", name: "Kevin" },
    { id: "5", name: "Matt" },
]

export const Restaurants: Restaurant[] = [
    {
        id: "1",
        name: "Bouillon Batingnoles",
        cuisine: "French",
        location: "Hollerich, Luxembourg",
        notes: "Purée so buttery it should come with a cardiologist",
        addedBy: "Kevin",
        visited: false,
        createdAt: new Date("2026-01-18"),
    },
    {
        id: "2",
        name: "Nanban",
        cuisine: "Japanese",
        location: "Place de Paris, Luxembourg",
        notes: "Ramen so noble it deserves a bow before slurping",
        addedBy: "Giovanni",
        visited: false,
        createdAt: new Date("2026-01-18"),
    },
    {
        id: "3",
        name: "Sodam",
        cuisine: "Korean",
        location: "Belair, Luxembourg",
        notes: "Fried chicken that makes you forget all life choice",
        addedBy: "Ambroise",
        visited: false,
        createdAt: new Date("2026-01-18"),
    },
    {
        id: "4",
        name: "Grand Café",
        cuisine: "French",
        location: "Place d'Armes, Luxembourg",
        notes: "French cuisine with a surprise Wäinzoossiss plot twist",
        addedBy: "Kevin",
        visited: false,
        createdAt: new Date("2026-01-18"),
    },
    {
        id: "5",
        name: "Levantine",
        cuisine: "Lebanese",
        location: "Gelle Fra, Luxembourg",
        notes: "French cuisine with a surprise Wäinzoossiss plot twist",
        addedBy: "Aurélien",
        visited: false,
        createdAt: new Date("2026-01-18"),
    },
    {
        id: "6",
        name: "Café Bel Air",
        cuisine: "Bar food",
        location: "Belair, Luxembourg",
        notes: "Come for the burgers, stay because someone ordered another round",
        addedBy: "Giovanni",
        visited: false,
        createdAt: new Date("2026-01-18"),
    },
]
