import LoaderPinwheel from "lucide-react/icons/loader-pinwheel"
import { useState } from "react"

import { BackgroundLayers } from "./background-decoration"
import { BrandIcon } from "./brand-icon"
const LoadingVerbs = [
    "Accomplishing",
    "Actioning",
    "Actualizing",
    "Allocating",
    "Analyzing",
    "Architecting",
    "Assembling",
    "Baking",
    "Balancing",
    "Beaming",
    "Beboppin'",
    "Befuddling",
    "Bending",
    "Billowing",
    "Blanching",
    "Bloviating",
    "Boogieing",
    "Boondoggling",
    "Booping",
    "Bootstrapping",
    "Bouncing",
    "Brewing",
    "Bubbling",
    "Buffering",
    "Bunning",
    "Burrowing",
    "Calculating",
    "Calibrating",
    "Canoodling",
    "Caramelizing",
    "Cascading",
    "Cataloging",
    "Catapulting",
    "Cerebrating",
    "Channeling",
    "Channelling",
    "Chiseling",
    "Choreographing",
    "Churning",
    "Circulating",
    "Clauding",
    "Clanking",
    "Clattering",
    "Coalescing",
    "Cogitating",
    "Combobulating",
    "Compiling",
    "Composing",
    "Computing",
    "Concocting",
    "Conjuring",
    "Considering",
    "Contemplating",
    "Converging",
    "Cooking",
    "Crafting",
    "Creating",
    "Crackling",
    "Crunching",
    "Crystallizing",
    "Cultivating",
    "Debugging",
    "Deciphering",
    "Decompressing",
    "Deconstructing",
    "Defragmenting",
    "Deliberating",
    "Deploying",
    "Determining",
    "Dilly-dallying",
    "Discombobulating",
    "Disentangling",
    "Distilling",
    "Doing",
    "Doodling",
    "Drafting",
    "Drizzling",
    "Ebbing",
    "Effecting",
    "Electrifying",
    "Elucidating",
    "Embellishing",
    "Enchanting",
    "Encoding",
    "Entangling",
    "Envisioning",
    "Evaporating",
    "Excavating",
    "Experimenting",
    "Fabricating",
    "Fermenting",
    "Fiddle-faddling",
    "Finagling",
    "Flambéing",
    "Flibbertigibbeting",
    "Flowing",
    "Flummoxing",
    "Fluttering",
    "Forging",
    "Forming",
    "Fractaling",
    "Frolicking",
    "Frosting",
    "Fusing",
    "Gallivanting",
    "Galloping",
    "Garnishing",
    "Generating",
    "Gesticulating",
    "Germinating",
    "Gitifying",
    "Glimmering",
    "Glitching",
    "Grooving",
    "Grinding",
    "Gusting",
    "Hacking",
    "Harmonizing",
    "Hashing",
    "Hatching",
    "Herding",
    "Honking",
    "Hullaballooing",
    "Hyperspacing",
    "Ideating",
    "Illuminating",
    "Imagining",
    "Improvising",
    "Incubating",
    "Indexing",
    "Inferring",
    "Infusing",
    "Inflating",
    "Inspecting",
    "Ionizing",
    "Jitterbugging",
    "Juggling",
    "Julienning",
    "Kneading",
    "Knitting",
    "Leavening",
    "Levitating",
    "Linking",
    "Lollygagging",
    "Looping",
    "Magnetizing",
    "Manifesting",
    "Marinating",
    "Meandering",
    "Meshing",
    "Metamorphosing",
    "Misting",
    "Modulating",
    "Moonwalking",
    "Moseying",
    "Mulling",
    "Multiplexing",
    "Mustering",
    "Musing",
    "Nebulizing",
    "Nesting",
    "Newspapering",
    "Noodling",
    "Normalizing",
    "Nucleating",
    "Optimizing",
    "Orbiting",
    "Orchestrating",
    "Oscillating",
    "Osmosing",
    "Overclocking",
    "Packaging",
    "Parsing",
    "Patching",
    "Perambulating",
    "Percolating",
    "Perusing",
    "Philosophising",
    "Photosynthesizing",
    "Pollinating",
    "Polishing",
    "Pondering",
    "Pontificating",
    "Pouncing",
    "Precipitating",
    "Prestidigitating",
    "Priming",
    "Processing",
    "Profiling",
    "Proofing",
    "Propagating",
    "Puttering",
    "Puzzling",
    "Quantumizing",
    "Queueing",
    "Razzle-dazzling",
    "Razzmatazzing",
    "Rebalancing",
    "Recombobulating",
    "Refactoring",
    "Refining",
    "Rehydrating",
    "Reindexing",
    "Reticulating",
    "Rewiring",
    "Roosting",
    "Ruminating",
    "Sautéing",
    "Scampering",
    "Schlepping",
    "Scrambling",
    "Scurrying",
    "Sculpting",
    "Seasoning",
    "Shenaniganing",
    "Shimmying",
    "Shuffling",
    "Sifting",
    "Simmering",
    "Skedaddling",
    "Sketching",
    "Slithering",
    "Smooshing",
    "Sock-hopping",
    "Soldering",
    "Spelunking",
    "Spinning",
    "Splicing",
    "Sprouting",
    "Stewing",
    "Stitching",
    "Sublimating",
    "Swirling",
    "Swooping",
    "Symbioting",
    "Synchronizing",
    "Synthesizing",
    "Tempering",
    "Tessellating",
    "Thinking",
    "Threading",
    "Thundering",
    "Tinkering",
    "Titrating",
    "Tomfoolering",
    "Topsy-turvying",
    "Transfiguring",
    "Transmuting",
    "Triangulating",
    "Twisting",
    "Turbulating",
    "Undulating",
    "Unfurling",
    "Unravelling",
    "Untangling",
    "Uploading",
    "Vectorizing",
    "Vibing",
    "Vortexing",
    "Waddling",
    "Wandering",
    "Warping",
    "Whatchamacalliting",
    "Whirlpooling",
    "Whirring",
    "Whisking",
    "Whittling",
    "Wibbling",
    "Wiggling",
    "Working",
    "Wrangling",
    "Zapping",
    "Zesting",
    "Zigzagging",
    "Zooming",
] as const

function randomVerb() {
    return LoadingVerbs[Math.floor(Math.random() * LoadingVerbs.length)]
}

export function LoadingPlaceholder() {
    const [verb] = useState(randomVerb)

    return (
        <div className="relative flex min-h-screen flex-col overflow-hidden bg-[#faf9f7] dark:bg-[#1a1918]">
            <BackgroundLayers />
            <div className="relative z-10 flex flex-1 items-center justify-center">
                <div className="flex flex-col items-center justify-center space-y-6">
                    <BrandIcon>
                        <LoaderPinwheel className="size-7 animate-spin" aria-hidden="true" />
                    </BrandIcon>

                    <p
                        className="text-lg text-neutral-600 dark:text-neutral-400"
                        style={{ fontFamily: "var(--font-body)" }}
                    >
                        {verb}...
                    </p>
                </div>
            </div>
        </div>
    )
}

export function Loading({ message, className }: { message?: string; className?: string }) {
    const [verb] = useState(randomVerb)

    return (
        <span data-slot="loading" className={className}>
            {verb}
            {message ? ` ${message}` : ""}...
        </span>
    )
}

export function LoadingInline({ message, className }: { message?: string; className?: string }) {
    return (
        <span data-slot="loading-inline" className={className}>
            <LoaderPinwheel className="size-4 animate-spin text-neutral-400" />
            {message && <span className="ml-2 text-neutral-500">{message}...</span>}
        </span>
    )
}
