import { createSignal } from "solid-js"
import LoaderPinwheel from "lucide-solid/icons/loader-pinwheel"

export function Loading(props: { message?: string; class?: string }) {
    const [verb] = createSignal(LoadingVerbs[Math.floor(Math.random() * LoadingVerbs.length)])

    return (
        <span data-component="loading" class={props.class}>
            {verb()}
            {props.message ? ` ${props.message}` : ""}...
        </span>
    )
}

export function LoadingPlaceholder() {
    const [verb] = createSignal(LoadingVerbs[Math.floor(Math.random() * LoadingVerbs.length)])

    return (
        <div class="relative flex min-h-screen flex-col overflow-hidden bg-[#faf9f7] dark:bg-[#1a1918]">
            <div
                class="pointer-events-none absolute inset-0 opacity-[0.02] dark:opacity-[0.03]"
                style={{
                    "background-image": `url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='0.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`,
                }}
            />

            <div class="pointer-events-none absolute inset-0">
                <div class="absolute top-0 left-0 h-full w-1/2 bg-linear-to-br from-flame-pea-100/40 via-transparent to-transparent dark:from-flame-pea-900/20" />
                <div class="absolute right-0 bottom-0 h-full w-1/2 bg-linear-to-tl from-orange-100/30 via-transparent to-transparent dark:from-orange-900/10" />
            </div>

            <div class="animate-float pointer-events-none absolute top-[20%] left-[10%] h-32 w-32 rounded-full bg-flame-pea-300/15 blur-[80px] will-change-transform" />
            <div
                class="animate-float pointer-events-none absolute right-[15%] bottom-[10%] h-24 w-24 rounded-full bg-orange-300/10 blur-[60px] will-change-transform"
                style={{ "animation-delay": "1s" }}
            />

            <div class="relative z-10 flex flex-1 items-center justify-center">
                <div class="space-y-6 text-center">
                    <div class="relative mx-auto">
                        <div class="absolute inset-0 animate-pulse rounded-full bg-flame-pea-500/20 blur-2xl" />
                        <div class="absolute inset-0 rounded-full bg-flame-pea-400/10 blur-xl" />
                        <div class="relative flex size-16 items-center justify-center rounded-2xl bg-linear-to-br from-flame-pea-500 to-flame-pea-600 text-white shadow-[0_8px_30px_rgb(181,57,32,0.3)] dark:from-flame-pea-600 dark:to-flame-pea-700 dark:shadow-[0_8px_30px_rgb(181,57,32,0.4)]">
                            <LoaderPinwheel class="size-7 animate-spin" aria-hidden="true" />
                        </div>
                    </div>

                    <p
                        class="text-lg text-neutral-600 dark:text-neutral-400"
                        style={{ "font-family": "var(--font-body)" }}
                    >
                        {verb()}...
                    </p>
                </div>
            </div>
        </div>
    )
}

const LoadingVerbs = [
    "Accomplishing",
    "Actioning",
    "Actualizing",
    "Allocating",
    "Analyzing",
    "Architecting",
    "Assembling",
    "Baking",
    "Balancing",
    "Beaming",
    "Beboppin'",
    "Befuddling",
    "Bending",
    "Billowing",
    "Blanching",
    "Bloviating",
    "Boogieing",
    "Boondoggling",
    "Booping",
    "Bootstrapping",
    "Bouncing",
    "Brewing",
    "Bubbling",
    "Buffering",
    "Bunning",
    "Burrowing",
    "Calculating",
    "Calibrating",
    "Canoodling",
    "Caramelizing",
    "Cascading",
    "Cataloging",
    "Catapulting",
    "Cerebrating",
    "Channeling",
    "Channelling",
    "Chiseling",
    "Choreographing",
    "Churning",
    "Circulating",
    "Clauding",
    "Clanking",
    "Clattering",
    "Coalescing",
    "Cogitating",
    "Combobulating",
    "Compiling",
    "Composing",
    "Computing",
    "Concocting",
    "Conjuring",
    "Considering",
    "Contemplating",
    "Converging",
    "Cooking",
    "Crafting",
    "Creating",
    "Crackling",
    "Crunching",
    "Crystallizing",
    "Cultivating",
    "Debugging",
    "Deciphering",
    "Decompressing",
    "Deconstructing",
    "Defragmenting",
    "Deliberating",
    "Deploying",
    "Determining",
    "Dilly-dallying",
    "Discombobulating",
    "Disentangling",
    "Distilling",
    "Doing",
    "Doodling",
    "Drafting",
    "Drizzling",
    "Ebbing",
    "Effecting",
    "Electrifying",
    "Elucidating",
    "Embellishing",
    "Enchanting",
    "Encoding",
    "Entangling",
    "Envisioning",
    "Evaporating",
    "Excavating",
    "Experimenting",
    "Fabricating",
    "Fermenting",
    "Fiddle-faddling",
    "Finagling",
    "Flambéing",
    "Flibbertigibbeting",
    "Flowing",
    "Flummoxing",
    "Fluttering",
    "Forging",
    "Forming",
    "Fractaling",
    "Frolicking",
    "Frosting",
    "Fusing",
    "Gallivanting",
    "Galloping",
    "Garnishing",
    "Generating",
    "Gesticulating",
    "Germinating",
    "Gitifying",
    "Glimmering",
    "Glitching",
    "Grooving",
    "Grinding",
    "Gusting",
    "Hacking",
    "Harmonizing",
    "Hashing",
    "Hatching",
    "Herding",
    "Honking",
    "Hullaballooing",
    "Hyperspacing",
    "Ideating",
    "Illuminating",
    "Imagining",
    "Improvising",
    "Incubating",
    "Indexing",
    "Inferring",
    "Infusing",
    "Inflating",
    "Inspecting",
    "Ionizing",
    "Jitterbugging",
    "Juggling",
    "Julienning",
    "Kneading",
    "Knitting",
    "Leavening",
    "Levitating",
    "Linking",
    "Lollygagging",
    "Looping",
    "Magnetizing",
    "Manifesting",
    "Marinating",
    "Meandering",
    "Meshing",
    "Metamorphosing",
    "Misting",
    "Modulating",
    "Moonwalking",
    "Moseying",
    "Mulling",
    "Multiplexing",
    "Mustering",
    "Musing",
    "Nebulizing",
    "Nesting",
    "Newspapering",
    "Noodling",
    "Normalizing",
    "Nucleating",
    "Optimizing",
    "Orbiting",
    "Orchestrating",
    "Oscillating",
    "Osmosing",
    "Overclocking",
    "Packaging",
    "Parsing",
    "Patching",
    "Perambulating",
    "Percolating",
    "Perusing",
    "Philosophising",
    "Photosynthesizing",
    "Pollinating",
    "Polishing",
    "Pondering",
    "Pontificating",
    "Pouncing",
    "Precipitating",
    "Prestidigitating",
    "Priming",
    "Processing",
    "Profiling",
    "Proofing",
    "Propagating",
    "Puttering",
    "Puzzling",
    "Quantumizing",
    "Queueing",
    "Razzle-dazzling",
    "Razzmatazzing",
    "Rebalancing",
    "Recombobulating",
    "Refactoring",
    "Refining",
    "Rehydrating",
    "Reindexing",
    "Reticulating",
    "Rewiring",
    "Roosting",
    "Ruminating",
    "Sautéing",
    "Scampering",
    "Schlepping",
    "Scrambling",
    "Scurrying",
    "Sculpting",
    "Seasoning",
    "Shenaniganing",
    "Shimmying",
    "Shuffling",
    "Sifting",
    "Simmering",
    "Skedaddling",
    "Sketching",
    "Slithering",
    "Smooshing",
    "Sock-hopping",
    "Soldering",
    "Spelunking",
    "Spinning",
    "Splicing",
    "Sprouting",
    "Stewing",
    "Stitching",
    "Sublimating",
    "Swirling",
    "Swooping",
    "Symbioting",
    "Synchronizing",
    "Synthesizing",
    "Tempering",
    "Tessellating",
    "Thinking",
    "Threading",
    "Thundering",
    "Tinkering",
    "Titrating",
    "Tomfoolering",
    "Topsy-turvying",
    "Transfiguring",
    "Transmuting",
    "Triangulating",
    "Twisting",
    "Turbulating",
    "Undulating",
    "Unfurling",
    "Unravelling",
    "Untangling",
    "Uploading",
    "Vectorizing",
    "Vibing",
    "Vortexing",
    "Waddling",
    "Wandering",
    "Warping",
    "Whatchamacalliting",
    "Whirlpooling",
    "Whirring",
    "Whisking",
    "Whittling",
    "Wibbling",
    "Wiggling",
    "Working",
    "Wrangling",
    "Zapping",
    "Zesting",
    "Zigzagging",
    "Zooming",
]
